# Generated by Django 4.2.5 on 2023-10-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactJs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uses', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Club',
        ),
    ]
