# Generated by Django 4.2.5 on 2023-10-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_reactjs_delete_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Django',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('djangoname', models.CharField(max_length=200)),
                ('use', models.IntegerField(default=0)),
            ],
        ),
    ]
