# Generated by Django 4.2.5 on 2023-11-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registerfr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.TextField()),
                ('password2', models.TextField()),
            ],
        ),
    ]
